urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.health_declaration, name='health-declaration'),
    path('swab_test_result/<int:pk>', views.SwabTestResultDetailView.as_view(), name='swab-detail'),
]

models.py
from django.db import models
from django.conf import settings
from django.core.validators import RegexValidator
from django.urls import reverse

SEX = (
    ('male', 'Male'),
    ('female', 'Female'),
    )

PERSONNEL_TYPE = (
    ('employee', 'Employee'),
    ('visitor', 'Visitor'),
    )

DIRECTION_TYPE = (
    ('i', 'Incoming'),
    ('o', 'Outgoing'),
)

RESULT = (
    ('-', 'Negative'),
    ('+', 'Positive'),
)

SWAB_TEST = (
    ('0', 'Standard Q Covid-19 Ag'),
    ('1', 'Standard F Covid-19 Ag FIA'),
)

MACHINE = (
    ('0', 'SD Biosensor F100'),
    ('1', 'SD Biosensor F200'),
)



BOOL_CHOICES = ((True, 'Yes'), (False, 'No'))

# Create your models here.
class HealthDeclaration(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    temperature = models.DecimalField(max_digits=3, decimal_places=1)
    personnel_type = models.CharField(max_length=8, choices=PERSONNEL_TYPE, blank=False)
    last_name = models.CharField(max_length=35)
    given_name = models.CharField(max_length=35, verbose_name='name')
    middle_name = models.CharField(max_length=35, blank=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    cellphone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    email = models.EmailField(null=True, blank=True)
    age = models.PositiveSmallIntegerField(null=True, blank=False)
    gender = models.CharField(max_length=6, choices=SEX, blank=False)
    department = models.ForeignKey('Department', related_name='health_declarations', on_delete=models.PROTECT)
    traveled_outside = models.BooleanField(choices=BOOL_CHOICES)
    exposed_to_suspected_probable_or_confirmed = models.BooleanField(choices=BOOL_CHOICES)
    seen_for_probability_or_suspicion = models.BooleanField(choices=BOOL_CHOICES)
    undergone_testing_or_swabbing = models.BooleanField(choices=BOOL_CHOICES)
    do_you_authorize_camillus_medhaven = models.BooleanField(choices=BOOL_CHOICES)
    headache = models.BooleanField(choices=BOOL_CHOICES)
    fever = models.BooleanField(choices=BOOL_CHOICES)
    cough_and_colds = models.BooleanField(choices=BOOL_CHOICES)
    sore_throat = models.BooleanField(choices=BOOL_CHOICES)
    shortness_of_breath = models.BooleanField(choices=BOOL_CHOICES)
    muscle_pains_or_body_weakness = models.BooleanField(choices=BOOL_CHOICES)
    joint_pains = models.BooleanField(choices=BOOL_CHOICES)
    diarrhea = models.BooleanField(choices=BOOL_CHOICES)
    loss_of_sense_of_smell_and_taste = models.BooleanField(choices=BOOL_CHOICES)

    class Meta:
        ordering = ('-date',)

    def __str__(self):
        return f'{self.date.strftime("%m/%d/%Y, %H:%M%p")} - {self.given_name} {self.last_name}'

class Department(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'department'

    def __str__(self):
        return self.name

class SwabTestResult(models.Model):
    patient = models.OneToOneField(HealthDeclaration, on_delete=models.CASCADE, primary_key=True)
    date = models.DateField(auto_now=False, null=False, blank=False)
    direction_to_work = models.CharField(max_length=1, choices=DIRECTION_TYPE, blank=True)
    day_of_quarantine = models.PositiveSmallIntegerField(null=True, blank=True) 
    specimen = models.CharField(max_length=160, blank=True)
    swab_test = models.CharField(max_length=1, choices=SWAB_TEST, blank=True)
    machine = models.CharField(max_length=1, choices=MACHINE, blank=True)
    COI = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    test_result = models.CharField(max_length=1, choices=RESULT, blank=False)
    photo = models.ImageField(
            null=True,
            blank=True,
            upload_to="photos/swab_test_results/%Y/%m/%D",
            )
    staff_nurse = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date',]

    def __str__(self):
        return f'{self.date} - {self.patient.last_name}, {self.patient.given_name} {self.patient.middle_name} ({self.get_test_result_display()})'

    def get_absolute_url(self):
        return reverse('swab-detail', args=[str(self.patient.id)])

templates/health_declaration/form.html
{% extends 'account/base.html' %}

{% block title %}Health Declaration Form{% endblock %}

{% block header %}
<header>
  {% include 'core/includes/navbar.html' %}
  <div class="card card-intro sky-gradient">
    <div class="card-body white-text rgba-black-light text-center">
      <!--Grid row-->
      <div class="row d-flex justify-content-center">
        <!--Grid column-->
        <div class="col-md-6">
          <h1 class="font-weight-bold h2">St. Camillus MedHaven Nursing Home Health Declaration</h1>
        </div>
      <!--Grid column-->
      </div>
    <!--Grid row-->
    </div>
  </div>
</header>
{% endblock %}

{% block content %}
  <div id="hd-form" class="d-flex justify-content-center align-items-center">
      <div class="col-lg-12 p-4">
      {% if form.errors %}
        <p>
          Please correct the following errors
        </p>
      {% else %}
        <p>In compliance with Republic Act 11332 (Mandatory Reporting of Notifiable Diseases and Health Events of Public Health Concern Act), You are required to provide truthful information about your health condition and possible exposure.

Moreover this is in compliance with the Company's Return to Work Policy for all employees and visitors.</p>
      {% endif %}
      {% load crispy_forms_tags %}
      {% crispy form form.helper %}
      </div>   
  </div>
{% endblock %}

templates/health_declaration/swabtestresult_detail.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Swab Test Result</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <style>
      ul li {
        display: inline-block;     
      } 
      table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
      }   
      .demogs {
        text-decoration: underline;
        margin-right: 40px;
      }
      .signature {
        text-decoration: overline;      
      }
      td {
        padding: 8px;
      }
      .emblem {
        float: left;
      }
    </style>
  </head>
  <body>
    <style type="text/css" media="print">
      .printbutton {
        visibility: hidden;
        display: none;
      }
    </style>
    <script type="text/javascript"> 
	   document.write("<input type='button' " +
        "onClick='window.print()' " +
        "class='printbutton' " +
        "value='Print This Page'/>");
    </script>    
    <div style="text-align: center;">
      <ul>
        <li><img class="emblem" src="https://scontent.fmnl10-1.fna.fbcdn.net/v/t1.6435-9/167595297_3930492120340224_7143982198573172424_n.jpg?_nc_cat=101&ccb=1-3&_nc_sid=973b4a&_nc_ohc=pXK8ivDRAREAX8Rjna-&_nc_ht=scontent.fmnl10-1.fna&oh=f1b69c1e228ba042bac1458c947ade88&oe=60A56CE3" alt="" width="60" height="60"></li>
        <li><h2 style="text-align: center; color: green;">St. Camillus MedHaven</h2><h6>St. Camillus MedHaven Nursing Home</h6></li>
        <li><img class="emblem" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.K7Ht7PtG6NYnQX4g6oWpAwHaKl%26pid%3DApi&f=1" alt="" width="60" height="60"></li> 
      </ul>
      <small>#29 Apitong St., Marikina Heights, Marikina City</small>
    </div>    
    <br>
    <h6 style="text-align: center;	">HEALTH DECLARATION FORM</h6>
    <br>
    <ul style="list-style-type: none;">
      <small>Name: <span class="demogs">{{ swabtestresult.patient.given_name }} 
      {% if swabtestresult.patient.middle_name %}
        {{ swabtestresult.patient.middle_name }}
      {% endif %}
        {{ swabtestresult.patient.last_name }}</span>
      </small>
      <li><small>Age: <span class="demogs">{{ swabtestresult.patient.age }}</span></small></li>
      <li><small>Sex: <span class="demogs">{{ swabtestresult.patient.gender }}</span></small></li>
      <li><small>Date: <span class="demogs">{{ swabtestresult.date }}</span></small></li>
    </ul>
    <ul>
      <li><small>Department/section: <span class="demogs">{{ swabtestresult.patient.department }}</span></small></li>
      <li><small>Contact no.: <span class="demogs">{{ swabtestresult.patient.cellphone_number }}</span></small></li>
      <li><small>Body Temperature: <span class="demogs">{{ swabtestresult.patient.temperature }}</span></small></li>
    </ul>
    <br>
    <p><small>In the past 7 days, have you or any member of your household, travelled to any areas with known case of Covid-19?</small></p>
      <small><input type="checkbox" disabled="true"{% if swabtestresult.patient.traveled_outside %} checked="true"{% endif %}>
      <label> Yes</label>
      <input type="checkbox" disabled="true"{% if not swabtestresult.patient.traveled_outside %} checked="true"{% endif %}>
      <label> No</label></small>
    <p><small>In the past 7 days, have you or any member of your household has had any contact with any Covid-19 biological material?</small></p>
      <small><input type="checkbox" disabled="true"{% if swabtestresult.patient.exposed_to_suspected_probable_or_confirmed %} checked="true"{% endif %}>
      <label> Yes</label>
      <input type="checkbox" disabled="true"{% if not swabtestresult.patient.exposed_to_suspected_probable_or_confirmed %} checked="true"{% endif %}>
      <label> No</label></small>
    <p><small>Have you had history of fever for the last 7 days?</small></p>
      <input type="checkbox" disabled="true"{% if swabtestresult.patient.fever %} checked="true"{% endif %}>
      <small><label> Yes</label>
      <input type="checkbox" disabled="true"{% if not swabtestresult.patient.fever %} checked="true"{% endif %}>
      <label> No</label></small>
    <p><small>Have you had any symptoms in the last 7 days such as:</small></p>
    <p><small>If Yes:</small></p>
      <small><input type="checkbox" disabled="true"{% if swabtestresult.patient.cough_and_colds %} checked="true"{% endif %}>
      <label> Colds or</label>
      <input type="checkbox" disabled="true"{% if swabtestresult.patient.cough_and_colds %} checked="true"{% endif %}>
      <label> Cough</label>
      <input type="checkbox" disabled="true"{% if swabtestresult.patient.loss_of_sense_of_smell_and_taste %} checked="true"{% endif %}>
      <label> Loss of taste or</label>
      <input type="checkbox" disabled="true"{% if swabtestresult.patient.loss_of_sense_of_smell_and_taste %} checked="true"{% endif %}>
      <label> Loss of smell</label>
      <input type="checkbox" disabled="true"{% if swabtestresult.patient.muscle_pains_or_body_weakness %} checked="true"{% endif %}>
      <label> Muscle pain</label>
      <input type="checkbox" disabled="true"{% if swabtestresult.patient.sore_throat %} checked="true"{% endif %}>
      <label> Itchiness in the throat/sore throat</label></small>
      <p><small><input type="checkbox" disabled="true"{% if swabtestresult.patient.shortness_of_breath %} checked="true"{% endif %}>
      <label> Shortness of breath/Difficulty of Breathing </label>
      <input type="checkbox" disabled="true"{% if swabtestresult.patient.joint_pains %} checked="true"{% endif %}>
      <label> Myalgia</label></small></p>
      
      <p><small>DECLARATION:</small></p>
      <p><small>I, hereby certify that the above information is true and complete. I understand that my failure to answer, or any false misleading information given by me, may be used as a ground for the filing cases against me under Articles 171 and 172 of the revised Penal Code of the Philippines, or Republic Act No. 11332, otherwise known as the “Law on Reporting Communicable Disease”.</small></p>
      <p><small>I authorize Camillus MedHaven nursing home to conduct collection and testing by using Covid-19 Antigen test through nasopharyngeal swab as part of the infection control policy.</small></p>
      <p><small>I, authorize my test result to be disclosed to the government entity as may required by law.</small></p>
      <p><small>I acknowledge that a positive test result is an indication that I must self-isolate to prevent the spread of the infection. I also allow them to report the case to the authority for proper intervention.</small></p>
      <p><small>I understand that as with medical test, there is the possibility of false negative or false positive Covid-19 result.</small></p>
      <p><small>I, the undersigned have been informed about the test purpose, procedure, possible benefits and risk. I have given the opportunity to ask questions before I sign. I voluntarily agree to this testing for Covid-19.</small></p>
      <br>
      <p><small><span class="signature">Printed Complete Name and Signature </span></small></p>
      <table>
        <tr>
          <td> 
            <small>Name: {{ swabtestresult.patient.given_name }} 
              {% if swabtestresult.patient.middle_name %}
                {{ swabtestresult.patient.middle_name }}
              {% endif %}
                {{ swabtestresult.patient.last_name }}
            </small> 
          </td>
          <td>
            <small><label>SD Biosensor F100 Machine: </label>  
            <input type="checkbox" disabled="true"{% if swabtestresult.machine == '0' %} checked="true"{% endif %}></small>            
          </td>
          <td>
            <small><label>SD Biosensor F200 Machine: </label>  
            <input type="checkbox" disabled="true"{% if swabtestresult.machine == '1' %} checked="true"{% endif %}></small>
          </td>
        </tr>
        <tr>
          <td> 
            <small>Date: {{ swabtestresult.date }}</small>
            </small> 
          </td>
          <td>
            <small><label>STANDARD F COVID-19 Ag FIA: </label>  
            <input type="checkbox" disabled="true"{% if swabtestresult.swab_test == '1' %} checked="true"{% endif %}></small>            
          </td>
          <td>
            <small><label>STANDARD Q COVID-19 Ag: </label>  
            <input type="checkbox" disabled="true"{% if swabtestresult.swab_test == '0' %} checked="true"{% endif %}></small>
          </td>
        </tr>
        <tr>
          <td><small>Age: {{ swabtestresult.patient.age }}</small></td>
          <td rowspan="5" colspan="2"><div class="text-center"><img class="img-fluid" src="{{ swabtestresult.photo.url }}" alt="" width="199" height="300"></div></td>
        </tr>
        <tr>
          <td><small>Specimen: {{ swabtestresult.specimen }}</small></td>
        </tr>
        <tr>
          <td><small>{{ swabtestresult.get_direction_to_work_display|upper }} </small><p><small>Day: {{ swabtestresult.day_of_quarantine }}</small></p></td>
        </tr>
        <tr>
          <td><small>COI: {{ swabtestresult.COI }}</small></td>
        </tr>
        <tr>
          <td>
            <p><small>COVID-19 ANTIGEN RESULT</small></p>
            <p><small><label>Negative</label> <input type="checkbox" disabled="true"{% if swabtestresult.test_result == '-' %} checked="true"{% endif %}>
            </small></p>
            <p><small><label>Positive</label> <input type="checkbox" disabled="true"{% if swabtestresult.test_result == '+' %} checked="true"{% endif %}>
            </small></p>
            <p>
              <small><strong>*If positive better Isolate and for RTPCR test </strong></small>
            </p>
            <br>
            <p>
              <small><span class="signature">Nurse-in-charge Printed Name and Signature</span></small>
            </p>
          </td>
        </tr>
      </table>
  </body>
</html>